name: awesome_scroller
description: Animated Flutter ScrollView package which synchronize Animations with PageView. You and add any child widget inside Awesome Scroller and scroll the list.
version: 0.0.14
homepage: https://github.com/hamza-rizvii/awesome_scroller

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

